ruby '2.6.2'
source 'https://rubygems.org'

gem 'color-converter'
gem 'configatron'
gem 'eventmachine'
gem 'faye-websocket'
gem 'huey'
gem 'oj'
gem 'paint'
gem 'rest-client'
gem 'tty-prompt'
gem 'websocket-eventmachine-client'
